### ISSUE TITLE
Abort on active rspec `--focus` option

### ISSUE THREAD

**Issue by mockdeep** [mbj/mutant#123]
When I add the following config to my spec_helper file all mutations fail except the noop:

``` ruby
config.filter_run :focus => true
```

**Comment by backus** [comment]
Not usually one to bump issues, but I got burned by this for like an hour since I had a totally unrelated spec focused and mutant reports the selected tests as having run. Would good be a nice thing to fix. I'd be happiest with something that aborts if the selected tests gets filtered down to zero when focus filter is applied

**Comment by mbj** [comment]
@backus same here, so will definitively add it soon thanks for bumping. I'm getting more and more mutant time recently.

**Comment by mbj** [comment]
8y ;)

**Comment by mbj** [comment]
@backus, @dgollahon 

I opted for doing something "generic", not scoped to rspec/minitest integrations but simply: Whenever you request mutant to run on 0 effective tests: It prints a nice warning message aborting early.

Next step is to print the message on 0 *selected* tests.

**Comment by mbj** [comment]
@backus it could actually be you need a slight change from what I did, in making mutant complain on having 0 selected tests, as the focus option may keep 1-2 tests of 1k in?
