### ISSUE TITLE
Add mutation from `to_h` -> `to_hash`?

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#218]
The semantics of these are currently unknown but maybe valid as a mutation. References #217.

**Comment by aprescott** [comment]
I'm not sure I understand this or #217.

If an object responds to `to_str`, then it can really act like a string. If it responds to `to_s`, then it can be coerced into a string representation. The same thing goes for `to_int` vs `to_i`. Changing a method from `to_i` to `to_int` is a change in semantics.

**Comment by mbj** [comment]
@aprescott Mutant mutates to "semantic simplest operation that does the job".

If an object that declares to be acting as a string via `#to_str` should be used via `#to_str`. So the mutation from `#to_s` (a weaker form as string a-like-acting) to `#to_str` forces to use the simplest available operation that does the job.

If you see an alive mutation from `#to_s` to `#to_str` you really meant to use `#to_str` where you have `#to_s` right now.

Anotherway to view this: `#to_str` is the supertype of the `#to_s` interface. `#to_s` is more "broad" than `#to_str`. We should always use the simplest possible interface that does the job. The less powerful a tool is the less likely something goes wrong on use.

If you have a polymorphic receiver type where not ALL objects you call `#to_s` on will implement `#to_str` mutant will not report the '#to_s` to `#to_str` mutation as alive, as there is a counter example.

Always using the simplest possible composition of primive that does the job is a nice deterministic baseline developers can follow to end up in the same solution for the same problem. It reduces:

* Review overhead (when everyone uses the same axioms, its less likely there will be a code flag to address)
* Likeliness of bugs, as less powerful compositions / primitives simply reduce the chance you do something you did not intend
* Specification overhead: The less semantics you implement the less semantics you need to test for.

All mutation operators in mutant are derived from "mutate powerful thing into less powerfull thing". Sequences of operations `a; b` into `a`. Method chains from `foo.bar.baz` to `foo.baz` etc. If something is redundant you can A) remove the extra ssemantics  B) specify it (in case you really need it, but your spec right now does not). Most of the mutations are actually killed by A) these days.

**Comment by dkubb** [comment]
@aprescott another thing this mutation points out if an assumption being made in the code that isn't reflected in the tests.

Say you have a simple method like this: (please excuse this extremely simple example)

```ruby
# the code
def to_string(object)
  object.to_s
end

# the test
describe '#to_string' do
  it 'returns a string' do
    expect(subject.to_string('test')).to be_kind_of(String) 
  end
end
```

Now mutant will mutate the specific code to `#to_str` and since the test will continue to pass mutant will notify you. You look at this and think "actually, I expect this method to accept a String *or* a Symbol object". So then you change the test to actually reflect that:

```ruby
describe '#to_string' do
  it 'returns a string' do
    expect(subject.to_string(:test)).to be_kind_of(String) 
  end
end
```

Alternatively you might think "you know, I only expect stuff that are `String` or support the String interface, so `#to_str` is good enough; I don't need to use a more generic interface, a more precise interface is better".

What mutant does is shows you less powerful primitives that can do the same job as the code you wrote and helps you follow the [Rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power) in your interface design.

**Comment by aprescott** [comment]
Amazing comments, thank you! I clearly misunderstood. :)

**Comment by tjchambers** [comment]
I experience this daily with mutant. I either find code I can (should!) remove as unnecessary, or strengthen weak tests to represent intent aka @dkubb example. I find this extremely valuable and focusing.

**Comment by dkubb** [comment]
> I clearly misunderstood

@aprescott thanks for questioning it though. Both @mbj and I have worked together for a while and it's good for us to explain our reasoning since it may not always be obvious. If there's anything else that is not clear, please don't hesitate to ask. It helps us solidify our understanding to explain it to others too.

We need to blog more about our development style both in general and with mutant ;)

**Comment by mbj** [comment]
> @aprescott thanks for questioning it though.

Yeah, please raise any questions. Each time we have to answer questions our understanding greatly improves.

**Comment by tjchambers** [comment]
@aprescott As an outsider benefitting from mutant and these types of questions I will add my appreciation too. 

I experience @mbj  and @dkubb as very opinionated. And as such rather than rationalize or *defend* their opinions, they are quite happy and comfortable sharing their reasoning, and in the same vain are willing to reconsider their thinking through dialogues such as this. I find this very helpful in getting a deep understanding of intent AND it has driven me to make more informed recommendations that align with the underlying philosophy and extend the power of mutation testing through this OS project.

Still very much a noob at this myself. SO I too appreciate the dialogue.

**Comment by aprescott** [comment]
It's excellent to see not only such a thorough response to a question, but an explicit welcome invitation. I definitely wasn't expecting such a fully-formed, clearly written answer.

**Comment by mbj** [comment]
Another way to argue here is:

> Changing a method from to_i to to_int is a change in semantics.

But the `#to_int` is a subset of the `#to_i` semantics. And thats the whole point of mutation testing. Mutating to subset of semantics to prove A) unspecified needed behavior B) dead code (semantics).

**Comment by dkubb** [comment]
OT but if anyone is interested in watching how @mbj and I debate different techniques, feel free to watch https://github.com/MountainRoseHerbs/spree. This is a project we're working on for a client and our pull requests often include lots of back and forth discussion about specific techniques.

Our client's private repos have even more discussion but we can't open them for obvious reasons ;)

**Comment by mbj** [comment]
Out spree repo is particularly interesting for people interested in MA as it is compared to our recent work:

* Weakly structured
* Not very well semantically covered
* A very high entropy code base in all dimensions. Style / Coverage / Architecture / Churn.

So its a good candidate to show how MA helps even in legacy code bases.

During our commercial activities that have to use spree for historic reasons, we discover lots of bugs in the spree code base. Most of them are exposed through the constraints we have in our client specific code. The ones we decided to fix on the spree side are:

* Mutation covered (through we limit mutation coverage to the code we actually touch)
* Developed via set of commits where each commit has to pass CI for its own (we call it hygienic commit), eases rebasing and upstreaming a lot.

Feel free to ask any question on any commit there. Sadly upstream does not follow all our recommendations so our approach does not translate for spree in high efficiency. For example they reject global style fixes (currently, trying to convince them).

Also relevant is the mutant repository itself. Mutant "recently" became stable self hosting, so we begun to backfill missing mutation coverage. Also we are not bound to (IMO suboptimal) upstream policy there so the approach we try to follow should be more visible.

**Comment by backus** [comment]
Still interested in this mutation @mbj or @dkubb?  I'm looking for some softball mutations I could contribute to the project

**Comment by mbj** [comment]
> Still interested in this mutation @mbj or @dkubb? I'm looking for some softball mutations I could contribute to the project

The ticket would be closed if we where not interested. Hint: Adding this mutation is super easy. But I do not want to spoil the discovery process (unless you ask me for it) breadcrumbs:

* Run `bundle exec parser -e '$the_source_you_wanna_mutate'` and `bundle exec parser -e '$the_source_you_wanna_mutate_to'
* Read the [AST-Documentation](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md) for the node that gets mutated
* Add the mutation to the expected mutations in the mutant [meta](https://github.com/mbj/mutant/tree/master/meta)
* See the specs fail
* Change code till specs pass
* Keep your commit sane & PR

**Comment by mbj** [comment]
@backus ^^ // forgot to @ mention you and want to trigger a notification, dunno if editing you in later does so.

**Comment by backus** [comment]
Thanks!  Will probably open a PR soon
