### ISSUE TITLE
String == and eql? are equivalent

### ISSUE THREAD

**Issue by crimsonknave** [mbj/mutant#302]
For strings (and some other objects, I assume) == and eql? are equivalent. This makes the mutation that converts == to eql? pointless. Personally, I find == much easier to read, so having mutant want to replace it with eql? is annoying.

I'm not sure if there's a way to not use some mutations for different classes.

**Comment by mbj** [comment]
On strings yes. On other objects not. Mutant does not know the types of message send receivers, and mutant cannot know that `#==` is equivalent to `#eql?` or not.

The mutation from `#==` to `#eql?` is derived from the core axiom I derive mutation operators from: Replace a powerful "thing" with a less powerful "thing". `#==` does more than `#eql?` because for some receivers `#==` coerces where `#eql?` does not.

Replacing `#==` to `#eql?` catches bugs for me. To me aesthetics of the source code are important to me, but bug-free software is more. So I do not see a reason to avoid this mutation.

I'd accept patches that add type specific behavior, so certain cases can be white-listed. But given my very limited OSS time I'll not do this by myself.

There is a ticket for runtime expression type detection already: #243.

**Comment by mbj** [comment]
I'll close this issue now, since I think I outlined the reasons why this mutation exists. In case you want to continue the discussion feel invited.
