### ISSUE TITLE
Mutant not mutating all executed code?

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#305]
How does mutant decide which parts of the code should be mutated?

I have something like this (this is only a mock):

    module Test
        def delete
            if something
                call_m1
            else
                call_m2
            end
        end
    end

I'm running mutant on Test#delete. I've noticed that it correctly mutates all code inside delete method, but doesn't mutat code in call_m1 or call_m2 methods. It tries replacing call_m1 with nil and self, but that's it.
Am I missing something? Is this something that mutat shouldn't do?

call_m1 and call_m2 are marked as private, but I get the same result after making them public.

**Comment by mbj** [comment]
@knovoselic Thx for your question, while you reduced the question (I appreciate it) it does not give me enough details to give you a short instance specific answer. This is not your fault since you are new to the subject.

Too answer this question broad and probably cover your case (and also to produce a bit of documentation for the future) I need to introduce a bit of mutant specific terminology terminology here.

Mutant performs the following steps:

* Subject discovery
* Subject specifc mutation generation
* Subject specific test selection
* Mutation killing

### Subject Discovery

In subject discovery phase it expands your CLI expression into a list of subjects. Currently two subject types are implemented, instance methods and singleton methods (aka class methods). There could be more in future like constant literals, class level DSL code etc.

An expression like `Test*` tries to find all constants that match the regexp `Test.*` via object space and than it uses reflection to find instance and singleton methods on that constants. Your instance method `#delete` would get found and selected for mutation analysis because its `UnboundMethod` Object has a non `nil` `#source_location`.

This source location returns a tuple of `(String, Fixnum)` where the first item is the file and the 2nd the line number. Mutant parses the file, and tries to match the AST returned by the parser against the line number to find the subset of the AST that represents the subject.

In your case this will identify the `def` node holding your method. This makes the subject with the narrow expression `Test#delete` available for analysis.

### Subject specific mutation generation

Mutant emits recursively all mutations for the node of the current subject. In your case it'll first call the mutation emitter for `def` nodes, than the one for `if` nodes, and the one for the two `send` nodes per branch of the if node. It does NOT mutate the implementation of the methods `call_m1` or `call_m2` *unless* your CLI expression would select those for mutation testing.

So if `call_m1` and `call_m2` are part of *your* namespace, they'll be mutated also, but in case these are from a 3rd party library (example ActiveRecord) you'll not see them mutated. This is by intention.

### Subject specific test selection

Currently mutant selects tests per subject via matching the longest prefix of the tests description.

So for your subject with expression `Test#delete` mutant first tries to find tests with description prefix `Test#delete` if that yields an empty list it tries prefix `Test`. It stops finding tests for the first non empty results.

### Mutation killing

For each mutation (on a subject) mutant a killfork is made for reasons that do not fit here. Inside the kill form the mutation is inserted via a generated monkeypatch, than the subject specific tests are tried to kill the mutation. In case one of these selected test fails the mutation counts as killed.

So in case you have a private method subject, you should have a test on the public interface being selected. Which is typially the case naturally. You adda test for public `Foo#bar` that calls private `Foo#baz`, `Foo#baz` does not have a test so selection tries tests for `Foo*` finding your test for `Foo#bar` that kills the mutations on `#baz`.

I hope this answers all your questions. So I'm gonna close this question for now. Feel free to continue discussion, and ask for anything I should clarify.
