### ISSUE TITLE
Execute all neutral (noop) mutations first and fail early.

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#308]
This gives far better feedback than executing them just before each subject.

**Comment by mbj** [comment]
We do not want this as noop mutations need to be intermixed with evil ones to capture concurrency leaks (or at least have a chance to).

**Comment by dgollahon** [comment]
> We do not want this as noop mutations need to be intermixed with evil ones to capture concurrency leaks (or at least have a chance to).

Would it be possible to do something where `mutant` has an option to fail fast on noop? That way it doesn't always get executed first per your ordering concern above but it would have saved me a lot of time over the years. I don't tend to use `--fail-fast` because it takes too long to resume and I like to be able to fix several mutations at once but when I have a neutral failure I have to wait a while to get feedback.

**Comment by mbj** [comment]
@dgollahon yes, thats certainly possible but a different case. thats more "dependent mutation" category captured elsewhere.
