### ISSUE TITLE
unused inheritance

### ISSUE THREAD

**Issue by andrzejkrzywda** [mbj/mutant#328]
I'm not sure if it makes sense for mutant to detect unused inheritance. I've prepared a small example showing what could possibly be detected here:

https://github.com/andrzejkrzywda/mutant_inheritance_example

Please note, that it's not a real world requirement, just a theoretical situation.

**Comment by mbj** [comment]
@andrzejkrzywda I think that this example is not relevant, because it violates the LSP principle.

The parent class `Foo` does have a significant different interface from the supclass `Bar`, `Foo` and `Bar` are not interface compatible to each other.

I think that this case is more relevant:

```
class Foo
  def bar
    1
  end
end

class Boz < Foo
  def bar
     1 + 0 # different implementation but same semantics than in superclass
  end
end
```

Mutant could than mutate the implementation of `Boz#bar` away, and-or replace it with `super`, allowing to spot unused / unusefull inheritance.

I think that I answered the question, so I'll close the issue. Feel free to continue.
