### ISSUE TITLE
question: incorrect code generated but still alive mutant

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#363]
This is just for my own education.

I am seeing mutations such as 

```
- activity << 'do this'
+ nil << 'do this'
```

and

```
- activity << 'do this'
+ self << 'do this'
```

I do not dispute this is a valid and useful mutation. However when this code is generated and tested with mutant the mutation is not always killed.

My inference from it not being killed even though it is non-executable as mutated is that path is not covered by my specs - either because the method was not covered, or that path in the code containing that line is never executed (which would cause a run time error of some severity like NoMethodError nilClass not having a  '<<' method).

Is my inference accurate? I ask so that when I see this type of a mutation it should suggest that my code path execution is skipping that line in my specs.

**Comment by tjchambers** [comment]
To further expand on my question my inference is that the following is correct:

- If mutated code would generate a runtime error (e.g. NoMethod Error) 
AND 
- the mutated code is actually in the execution path of a spec

THEN
- the mutated code will result in a killed mutation.

**Comment by mbj** [comment]
> To further expand on my question my inference is that the following is correct:
> 
> If mutated code would generate a runtime error (e.g. NoMethod Error) AND
> the mutated code is actually in the execution path of a spec
> THEN
> 
> the mutated code will result in a killed mutation.

Correct.

> (the caveat being that there is not code elsewhere that rescues the error)

Correct. You should not rescue generic exceptions in your code anyway.

**Comment by mbj** [comment]
@tjchambers I think you might run into a specific thought trap:

given the following code:

```ruby
bar
foo << baz
```

And under the assumption this fragment does NOT have any specs right now.

Will among others generate and report the following mutations as alive:

Remove of full 2nd statement

```ruby
bar
```

Mutation to singleton expressions in receiver of the 2nd statement:

```ruby
bar
self << baz
```

The 2nd mutation is kinda redundant in this scenario (no specs at all), because the first alive mutation already proved the full 2nd statement in the code fragment is not specified. So recursing into the 2nd statement does not increase your direct knowledge about unspecified behavior.

With more advanced semantic analysis & feeding back kill results from earlier mutations into the generator it would be possible to avoid to emit the 2nd mutation, and only get that one emitted when the first mutation I show here is killed.

But I refused to do this for the following reason:

I'm more efficient when I kill many mutations at once. If I'd only get presented the "next alive mutation" I have to do more iterations to discover the next one after I killed the first one. This is for me much more efficient than if I where implementing the feedback mode.

Questions should be answered IMO so I'll close this issue. Feel free to continue discussion.

**Comment by tjchambers** [comment]
@mbj thanks for your extensive answer. 

My intent is to learn from looking at my alive mutations what they indicate in my specs/code. When I have code that requires a configuration of spec that is not presented, then it is rather obvious what I need to do. This usually results for me from a combination of conditions on a single statement line, where some may not be necessary for a predicate to result in the proper path, and when removed through mutation show they are not required. 

However there are cases like the above that do not immediately suggest what is lacking in my specs and hence requires me to consider other possible reasons for the alive mutation. 

In summary for my own experience - code that is exercised in specs leaving an alive mutation is most often a case of incomplete configuration or a missing expectation. Code that IS not covered in specs *can* result in mutated code that is on the surface not executable without generating run time errors - therefore signaling a lack of path coverage. 

Of course there are exceptions in both cases. My intent is to be able to rapidly triage the underlying cause for an alive mutation over time to get swifter at assessing the action to take. 

OT - my "standard" that I am trying to adhere to is to have spec examples for EVERY public method in a class. I have yet to find a tool which surfaces this upon static evaluation of my source + specs. Mutant comes closest to this, but does so in a reverse manner - it shows me by example that all of the specs fail to cover the methods mutations. If you know of such a static tool that would (rubocop like) surface these gaps in my adherence to standard it would be good to know.

**Comment by dkubb** [comment]
> my "standard" that I am trying to adhere to is to have spec examples for EVERY public method in a class.

I mentally view a public method as if all of it's private methods were inlined into a single method. I usually try to specify everything I possibly can by exercising the public interface. I'm ok with private methods being implicitly covered though, since if I can kill every mutation in it via the public interface then there are no dead code paths and it is fully tested.
