### ISSUE TITLE
Question: Is there a way to detect if test was started by mutant?

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#420]
I have small part of the code which uses DB and breaks mutant (it creates indexes on test DB). Is there a way to detect if specs are started by the mutant so I can do something like this:

    create_indexes unless Mutant.running?

**Comment by mbj** [comment]
@knovoselic Its possible to detect if mutant is the top-level executable via `$0 == 'mutant'`. But I highly recommend against using this, if mutant gets triggered from a rake task this will not work. Nor I think adding a documented / stable public API for such a detection is the right way to overcome issues with global state mutation.

Mutant runs in 2 phases:

1) Loading application / loading specs. (once, no concurrency)
2) Running a subset of specs to kill a mutation (lots of times, lots of concurrency)

You want to make sure that NO global visible side effect happens in phase 2). You could archive this via a hypothetical `Mutant.running?` API. But in most cases I think its better to move global side effects (like creating indexes) into phase 1). The `spec_helper.rb` is a good place for this. RSpec provides a `before(:suite)` hook that should get triggered in phase 1) by mutant.

If you already have `create_index` in phase 2), its also likely you'll have much more global DB side effects in phase 2). So I'd assume once you "blacklisted" index operation (via a hypothetical Mutant.running?) you'll seconds later run into another state race, so you begin adding more guard clauses resulting in a significant complexity bump. Because soon your specs are cluttered with "mutation testing specific behavior", and than running specs without mutant is not equivalent anymore to running specs with mutant. Reducing the overall value of your spec suite significantly.

So rule of thumb:

In phase 1) do as much work as possible, including global side effects
Phase 2) do the least amount of work, preventing global side effects.

If you have specs (so phase 2) ) that NEED global state mutations, writing to the database, calling remote APIs, creating files, you have the following choices:

* Ignore this spec for mutation testing, specifying the subjects in real unit tests (that do not hit the global state). Ignoring examples can be done via the (undocumented, but public API): `mutant: false` rspec metadata.
* Try to "instantiate" the global state per spec, so that it is hidden from other instances of the spec execution. For DBs transactions usually work fine. (In postgresql I had great success with enclosing DB hitting specs in serializable transactions that where never commited). Lots of other techniques for other types of global mutable state (remote service APIs) etc are known but cannot be enumerated here.
* Reduce mutants concurrency to a single thread. This way you can run even the most convoluted / global state inspected spec suite against mutation testing. Kinda slow obviously. `--jobs 1` does the trick.

Over the long term my projects that all use mutation testing heavily benefited from the "write the specs in a way they are mutation testing proof". Those specs tend to be easier, less complex in state setup etc.

So summary: No, such an API exists. And there are good reasons not even to think about providing such an API. Issue will be closed.

I need to write down a "Properties for a mutation testing ready spec - And mitigation strategies" guideline. Sorry for that not to exist. My time is very limited. Right now I "buffer up" facts in my responses to questions here to take them as input for a consolidated writing.

@knovoselic So feel free to discuss my arguments here, this will trigger more thoughts that will allow to come up with more consolidated documentation earlier.

**Comment by tjchambers** [comment]
@knovoselic Sadly - as a heavy user of mutant on Rails app - I concur with @mbj statements above. It is not an "easy way out" but it is IMHO a proper approach. My specs are better off for having considered mutation testing. I too am compiling a personal list of do's and don'ts re: mutation testing when it comes to spec'ing.

**Comment by dkubb** [comment]
> I too am compiling a personal list of do's and don'ts re: mutation testing when it comes to spec'ing.

@tjchambers Any chance we'll see this posted somewhere? I love to see how other people handle these kinds of things. Since mutation testing more "on the fringe" there's not really a ton of information in the wild for how to deal with things.

One thing I have noticed is that all changes I've made to make my code easier to mutation test also has the side effect of making it easier to test, produces faster running tests, better code, and ultimately less buggy software. I've also noticed I haven't had to make any sacrifices to code quality or other things in response to mutation testing either. It's often when you introduce a new dev technique that you have to make trade-offs with other things, but I haven't found that at all -- the constraints it imposes seem to have an additive effect with other techniques I use.

**Comment by tjchambers** [comment]
@dkubb interesting you should ask. I have been toying with where to put it ONLINE. I experience the same outcomes you listed, but I also experience some challenges that I have figured out how to work around - mostly due to ActiveRecord and Rails in general. Some of these are mutant (the tool) specific and are recorded as issues, and some of them are mutation testing (like how to kill a live mutation that is "complaining" about additional code that is a performance optimization - such as an extra .includes that mutant sees as unnecessary). 

I think I may just start a public repo for it, as it would seem better than hiding it in a wiki even on Github. And then have a readme with links to the *topics*. 

Any suggestions?

**Comment by mbj** [comment]
@tjchambers Why dont PR these into a `doc` directory?

**Comment by mbj** [comment]
> .includes that mutant sees as unnecessary

Why dont add message expectations? That the include is there is part of your desired behavior. So add a spec?

**Comment by tjchambers** [comment]
@mbj my internal dialogue is I am not confident enough with my does and dont's as illustrated by the .includes point. Adding these as message expectations (and even which class I would be expecting it on given it is an AR include) was not on my mind. It would seem that if I offered these up as PR it would push the burden back on you to respond to them, but that might be good as it would incite this sort of dialogue. 

I tend to test outcomes and in the .includes case what I was going for was an outcome that reduced the AR query count, so that is what I tested - that the query count was 1 and not 1+.

**Comment by tjchambers** [comment]
Just to be more clear, I have been compiling these using real examples of mutations from my code, and when I find a new pattern I capture it into Evernote with a description of what it represents and what I need to do to kill that style of mutation.

**Comment by mbj** [comment]
> I tend to test outcomes and in the .includes case what I was going for was an outcome that reduced the AR query count, so that is what I tested - that the query count was 1 and not 1+.

AR does not make it easy to assert the number of SQL statements, through that is possible to do. Also I tend to prevent hitting the database from unit tests for speed. So I think that asserting the includes where given via a message expectation make sense for me.

**Comment by mbj** [comment]
> Just to be more clear, I have been compiling these using real examples of mutations from my code, and when I find a new pattern I capture it into Evernote with a description of what it represents and what I need to do to kill that style of mutation.

We should serialize this into the mutant meta expansions we plan and discuss in: https://github.com/mbj/mutant/issues/395

**Comment by knovoselic** [comment]
@mbj  Thanks again for super detailed answer! @tjchambers Yeah, I agree with you and @mbj on all points. I'd prefer to do thing right than easy, and I think your answers just helped me to do that.

I've put my `create_indexes` call inside `rails_helper` file, after requires and before `RSpec.configure`. Now I've moved it into `config.before(:suite)` and it's working perfectly.
Any ideas why it didn't work outside `config.before(:suite)`? I've tried to confirm that `rails_helper` get's executed multiple times, but couldn't. My try was pretty primitive, so maybe that's a problem. I've just put this:

    File.open("test#{Thread.current.object_id.to_s(36)}", 'w') {}

before `RSpec.configure`.

**Comment by knovoselic** [comment]
Hm, I'm a little confused. I just put this in my `spec_helper`:

      config.before(:suite) do
        File.open('test', 'a') {|f| f.puts 'test' }
      end

and file `test` has 84 line, which is the number of mutations that were being tested. Is this a bug or have I misunderstood something? I thought code in `before(:suite)` would run only once.

**Comment by mbj** [comment]
> and file test has 84 line, which is the number of mutations that were being tested. Is this a bug or have I misunderstood something? I thought code in before(:suite) would run only once.

Seems that `before(:suite)` is run before all test executions, my mistake. So its phase 2). So you have to place it outside the `RSpec.configure` block.

**Comment by knovoselic** [comment]
Well that's strange, because when I place it outside the `RSpec.configure` block it doesn't work (mutant just hangs), but when I place it inside the `before(:suite)` block it works.

**Comment by mbj** [comment]
I'll double check my assumptions and report. Code outside RSpec.configure should just work fine. Its loaded in the boot phase without concurrency. If code hangs there it might be for the fact that rails did not setup a DB connection yet. Are you loading & expanding the rails autoloads before?

**Comment by knovoselic** [comment]
This is the only code before `create_indexes` is called:

    require 'spec_helper'
    require File.expand_path('../../config/environment', __FILE__)
    require 'rspec/rails'
    require 'sidekiq/testing'


It seems that my query to the DB is what hangs the mutant. This is the complete `create_indexes` method:

    def create_indexes(database_name = nil)
      db = if database_name.blank?
             Mongoid.default_session
           else
             Mongoid.default_session.with(database: database_name)
           end
      return unless db[:'system.indexes'].find(name: /^(?!_id)/).count == 0


      Rails.application.load_tasks
      Rake::Task['test:create_indexes'].invoke
    end

If I remove 

          return unless db[:'system.indexes'].find(name: /^(?!_id)/).count == 0

everything works, but then rake task is executed on each executing, instead of just when needed. Any idea how to fix this (or debug)?
