### ISSUE TITLE
Add mutation from `@foo` to `foo` (private send)

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#452]

**Comment by dkubb** [comment]
:+1: I can't believe we missed this one.

**Comment by tjchambers** [comment]
This sounds like a step in the wrong direction. How do you kill this type of mutation if you are using Concord and want to minimize the complexity of your code? Using a method instead of a variable has a performance penalty and is considered another branch in ABC terminology - it is another method call. 

It seems this is not to be *encouraged* by making it a mutation.

**Comment by mbj** [comment]
> Using a method instead of a variable has a performance penalty 

Honestly. I do not care about performance in Ruby if you switch a typical program away from private gettters to ivars you'll not see a measurable effect.

Maybe in a loop body after benchmarking it makes a difference. To me using a raw ivars is an optimization I use optionally, not per default.

> and is considered another branch in ABC terminology - it is another method call.

Also I do not care about ABC metrics more than about correctness.

Using a private getter method has one significant advantage over ivars: If you typo getters you get an exception, if you typo ivars: You get a `nil` and optionally a warning.

Typoed ivars that go unnoticed are a bug class that can be solved via defaulting to private getters.

Ruby is a low guarantee language, and the more bug classes we get a rid of the more small steps we do in mitigating this.

**Comment by tjchambers** [comment]
As always you make good sound points.

If I want to use ivars I should NOT be using Concord gem (IMO) because it is doing more than I desire. 

My preference is to be aware when I look at code whether I am using a method or an ivar. It seems I cannot have both in Ruby. 

Therefore I do support this mutation.

**Comment by mbj** [comment]
@tjchambers If no private getter exist (aka mutant is not used), mutant will not show the mutation as alive.

**Comment by tjchambers** [comment]
My inference is you meant aka if Concord is not used?

**Comment by mbj** [comment]
@tjchambers Concord just produces (by default) a private getter. You can have that one without concord involved. I just corrected my post above to be correct. Sorry for the typo.
