### ISSUE TITLE
getting mutant errors out the project (third libraries)

### ISSUE THREAD

**Issue by leonardoprg** [mbj/mutant#541]
Hello guys,

I have a rails project that use `paranoia` gem

I'm running  the command

`mutant --use rspec User*`

and it is getting errors like:

```
.rvm/gems/ruby-2.2.4/gems/paranoia-2.1.5/lib/paranoia.rb:219:3a35a
@@ -1,4 +1,4 @@
 def self.paranoia_scope
-  where(paranoia_column => paranoia_sentinel_value)
+  where(paranoia_column => self)
 end

```

How can I avoid/fix it?

**Comment by backus** [comment]
I assume you have something like

```ruby
class User
  acts_as_paranoid
end
```

and the problem is that the paranoia gem monkey patches ActiveRecord to add this method. When you invoke this method, it defines the method that you quoted in your issue: https://github.com/rubysherpas/paranoia/blob/9e0ec38e5f4d08d25c1bf1b63c1fe78208abe625/lib/paranoia.rb#L219-L221

Unfortunately the answer is that you can't avoid this because of this "design" choice from the paranoia gem which makes it impossible for mutant to understand that this method is being defined by a third party library.

**Comment by mbj** [comment]
@backus Is correct, unless mutant implements more "ruby evaluation" it cannot determine if its "your" code or not given the way paranoia defines a "method in a method" (a horrible antipattern anyway).

> How can I avoid/fix it?

Mutant considers the method to be defined in the class User, so it should be mutation covered from its POV. You can exclude it via `--ignore-subject User.paranoia_scope` as you "know" its not your responsiblity as inherited from a 3rd party lib.

**Comment by leonardoprg** [comment]
@backus @mbj 

maybe is better remove paranoia from the project.

for sure it's a horrible antipattern.

anyway Thanks guys,

**Comment by mbj** [comment]
> maybe is better remove paranoia from the project.

Mutation testing also causes backpressure to remove suboptimal gems infecting your code, yes.

> for sure it's a horrible antipattern.

Having a deleted state for a record or a record graph is not itself a very bad idea. But I think this is likely better to be reflected 2rst class than with `paranoia`.

**Comment by leonardoprg** [comment]
totally agree,

I prefer have good tests instead choice some library.
