### ISSUE TITLE
Running mutant with "--since master" blows up on master branch

### ISSUE THREAD

**Issue by troessner** [mbj/mutant#604]
Coming from [this Reek issue](https://github.com/troessner/reek/issues/937):

We're using `mutant` like this right now:

```
RUBY_THREAD_VM_STACK_SIZE=64000 bundle exec mutant --include lib --require reek --use rspec --since master --jobs 4 'Reek*'
```

This works well for pull requests, but running the same command on master branch blows up with:

````
{-timo-|-columbia-} => [~/dev/reek]
  ( $ (master)) RUBY_THREAD_VM_STACK_SIZE=64000 bundle exec mutant --include lib --require reek --use rspec --since master --jobs 4 'Reek*'
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
#<Method: Reek::Smells::NestedIterators::Iterator.[]> does not have a valid source location, unable to emit subject
#<Method: Reek::Smells::NestedIterators::Iterator.members> does not have a valid source location, unable to emit subject
#<Method: Reek::Smells::NestedIterators::Iterator.new> does not have a valid source location, unable to emit subject
#<UnboundMethod: Reek::Smells::NestedIterators::Iterator#depth> does not have a valid source location, unable to emit subject
#<UnboundMethod: Reek::Smells::NestedIterators::Iterator#exp> does not have a valid source location, unable to emit subject
#<UnboundMethod: Reek::Smells::NestedIterators::Iterator#line> is dynamically defined in a closure, unable to emit subject
fatal: No commit specified?
/Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/repository.rb:47:in `touches?': Command ["git", "log", "HEAD...master", "-L", "23,34:/Users/timo/dev/reek/lib/reek/ast/ast_node_class_map.rb"] failed! (Mutant::Repository::RepositoryError)
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/repository.rb:16:in `call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:19:in `block in call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `each'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `all?'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `public_send'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:19:in `block in call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `each'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `all?'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `public_send'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/morpher-0.2.6/lib/morpher/evaluator/predicate/boolean.rb:17:in `call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/matcher/filter.rb:15:in `select'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/matcher/filter.rb:15:in `call'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/env/bootstrap.rb:104:in `matched_subjects'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/env/bootstrap.rb:55:in `env'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/cli.rb:18:in `run'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/bin/mutant:39:in `<top (required)>'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/mutant:23:in `load'
	from /Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/mutant:23:in `<main>'
```

**Comment by mbj** [comment]
@troessner I've researched a bit. Summary: This is working as "designed", but the design is suboptimal. It stems from the fact that `git log -L` does exit nonzero when there is no commit selected by the source rnage. AKA when `--since $arg` equals `HEAD`.

The correct fixes would be:

1. Detect this case and noop from mutant already (possibly the simplest)
2. Find a git cli that allows the same functionality, but still exits zero (AFAIK there is none)
3. Use `git diff` and parse the output to intersect with subject ranges (the most correct, and also most future proof fix as only one subprocess is needed to cover the entire subject selection)

I do not have the energy for any of these, OSS especially for Ruby does not pay any of my bills. Nor I'm particularly interested in Ruby anymore.

As this case is not a problem for my current paying clients (where we use mutant, but with `--since HEAD~1` that always includes a commit) likely this issue will stay unaddressed.

There are two solutions you can carry out on your side:

* Use `--since HEAD~1` and build every commit in a PR (likely also a good workflow improvement)
* Do not pass `--since` on master (effectively do not run mutant there). Might be most easy to implement via logic like `run_mutant_with_since unless detect_ci && git_branch_is_master`.

Sorry for this unpleasant news, but I've to allocate my limited time wisely.

**Comment by troessner** [comment]
>> Sorry for this unpleasant news, but I've to allocate my limited time wisely.

No problem, I guess most of us have this issue :)

>> Do not pass --since on master (effectively do not run mutant there). Might be most easy to implement via logic like run_mutant_with_since unless detect_ci && git_branch_is_master.

I'll go ahead with that, thanks for explanation!

**Comment by mbj** [comment]
> No problem, I guess most of us have this issue :)

About to post a maintenance policy to not provide false hope. Summarzy: I'm okay with categorizing issues, explaining whats going on etc. But its unlikely I can fix stuff that does not concern my clients enviornments.

**Comment by backus** [comment]
@troessner you might want to consider this:

```sh
bundle exec mutant --since $(git rev-list origin/master~ --merges --max-count=1) --use rspec -- 'Reek*'
```

I use this in a private project. Basically, the `--since` flag here is being given the revision of the "second most recent merge commit on origin/master." A few perks:

* This command works if you are on a feature branch (it tests all mutations on that feature branch)
* This command works if you are running on master. It will test the changes on `HEAD` vs the previous merge commit on `origin/master`
* You should never have conflicts where `--since $arg` equals `HEAD`

**Comment by troessner** [comment]
@backus thanks for the idea - for now we solved it like [this](https://github.com/troessner/reek/pull/946/files). I'll keep your solution in mind in case we're re-evaluating this approach.
