### ISSUE TITLE
Feature request: Killing infinite (or long) loops automatically

### ISSUE THREAD

**Issue by filipvanlaenen** [mbj/mutant#87]
If a mutation creates an infinite (or very long) loop, mutant should be able to kill it. Some strategies:

1. Do a dry run of the specs, and measure how much time they take. If the specs take e.g. ten times more time after a mutation, kill the mutant automatically, is it probably caused an infinite loop. Users may want to override the default factor.

2. The same as 1, but per spec. This kills off infinite loops in fast specs quickly.

3. Kill off a mutant that takes more than a fixed amount of time. I.e. include the solution suggested in issue #81 as a feature of mutant, and let the user override the default amount of time.

4. Implement 3 together with either 1 or 2.

**Comment by mbj** [comment]
I'll close this feature request because I think its a bad idea.

The fundamental core idea of automated mutation testing is: Find mutations to the code that you could do, that do PASS your test suite *as is*.

If mutant would add an additional layer around your test suite: This is violated. The timeout should be done on the rspec / test-integration side.

Closing this issue.

**Comment by mbj** [comment]
@filipvanlaenen Mutant now has support for external coverage criteria that mitigate the reasons I did not want to have this behavior as a default, see: https://github.com/mbj/mutant/blob/master/docs/configuration.md#coverage_criteria
