### ISSUE TITLE
Add new mutation: "foo#{bar}" → 'foo#{bar}'

### ISSUE THREAD

**Issue by filipvanlaenen** [mbj/mutant#90]
Try replacing double quotes with single quotes. Removes the string interpolation, has also consequences for escaping.

"foo" vs 'foo'
"#{foo}" vs '#{foo}'
"foo\n" vs 'foo\n'

**Comment by dgollahon** [comment]
@mbj Is this still a desirable mutation?

> Change unparser to emit all string literals in the most "primitive" form. "foo" would get emitted as 'foo' . This is not a mutation only a representation change with absolutely the same semantics. "foo\n" would still be emitted as "foo\n".

I assume this is not currently a goal of `unparser` and seems strange to me for mutant to enforce since it is stylistic only.

> Add a mutation that escapes all escape sequences, so the now escaped literals would get emitted in the most primitive form, single-quoted. "foo\n" => 'foo\n'.

This seems like it might be a frustrating set of mutations because it mutates to something that is almost never what you want and may confuse newcomers. Since we already mutate to empty strings, mutate dstr nodes, etc. I am doubtful that this would yield many useful alives.

What's the current opinion on this one?

**Comment by mbj** [comment]
I consider that this mutation is not a good idea. Mutant only wants to remove or replace (without adding) execution semanitcs.

This suggested mutation does NOT fall into either category. Closing.
